Added and updated construct scripts

diff --git a/bin/construct b/bin/construct
--- a/bin/construct
+++ b/bin/construct
@@ -1,14 +1,41 @@
 #!/usr/bin/env bash
 
-hostname=`hostname`
-SPARK_HOME="/root/spark"
-bin="$(cd "`dirname "$0"`"; pwd)"
-JAR_PATH=`ls $bin/../target/annotation-search-*-jar-with-dependencies.jar`
+# Runs construct
+##
 
-$SPARK_HOME/bin/spark-submit \
-  --class edu.berkeley.cs.succinct.annot.example.SparkConstruct \
-  --master spark://${hostname}:7077 \
-  $JAR_PATH \
-  $@
+usage="Usage: construct [input] [output]"
 
+# if less than 2 args specified, show usage
+if [ $# -le 1 ]; then
+  echo $usage
+  exit 1
+fi
 
+bin="`dirname "$0"`"
+bin="`cd "$bin"; pwd`"
+
+. "$bin/succinct-config.sh"
+. "$SUCCINCT_PREFIX/bin/load-succinct-env.sh"
+
+JAR_PATH="$SUCCINCT_PREFIX/target"
+
+JAR_COUNT=0
+
+for f in "${JAR_PATH}"/annotation-search-*-jar-with-dependencies.jar; do
+  if [[ ! -e "$f" ]]; then
+    echo "Failed to find Annotation Search assembly in $JAR_PATH" 1>&2
+    echo "You need to build Annotation Search before running this program" 1>&2
+    exit 1
+  fi
+  ANNOTATION_SEARCH_JAR="$f"
+  JAR_COUNT=$((JAR_COUNT+1))
+done
+
+if [ "$JAR_COUNT" -gt "1" ]; then
+  echo "Found multiple Succinct Core assemblies in $JAR_PATH" 1>&2
+  ls "${JAR_PATH}"/annotation-search-*-jar-with-dependencies.jar 1>&2
+  echo "Please remove all but one jar." 1>&2
+  exit 1
+fi
+
+java -cp $ANNOTATION_SEARCH_JAR edu.berkeley.cs.succinct.annot.examples.Construct $@
